C =====================================================================
C  The basis-set tables of MOPAC 7, excerpted from
C    https://github.com/openmopac/MOPAC-archive
C    commit ed31531485fde27106e8e700fc8461b514923929, subdirectory 1993_MOPAC7
C    tree sha256 edaa50a6f0f581ea67241056f66c09e0919a6a922bacb4f57462d8ebdf55ee4c
C
C  GENERATED by scripts/generate-basis-tables.mjs. Do not edit.
C
C  It exists so src/basis/__tests__/basisTables.test.ts can re-parse
C  MOPAC's own Fortran on every machine and every CI run, where the
C  archive under build/ is absent. Every line below is copied verbatim
C  from the file and lines its header names, and the generator refuses
C  to write a table the excerpt does not reproduce.
C =====================================================================
C
C --- moldat.f 93-94: which exponent array each hamiltonian switches in
            ZS(I)=ZSM(I)
            ZP(I)=ZPM(I)
C
C --- moldat.f 125-126: which exponent array each hamiltonian switches in
            ZS(I)=ZSPM3(I)
            ZP(I)=ZPPM3(I)
C
C --- moldat.f 157-158: which exponent array each hamiltonian switches in
            ZS(I)=ZSAM1(I)
            ZP(I)=ZPAM1(I)
C
C --- moldat.f 230-231: which exponent array each hamiltonian switches in
               ZS(I)=ZS3(I)
               ZP(I)=ZP3(I)
C
C --- diat.f 38-40: NPQ, the principal quantum number of the valence shell
      DATA NPQ/1,0, 2,2,2,2,2,2,2,0, 0,3,3,3,3,3,3,0, 0,4,4,4,4,4,4,4,
     14,4,4,4,4,4,4,4,4,0, 5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5
     2,32*6,15*0,3,5*0/
C
C --- diat.f 142-142: the bohr MOPAC 7 computes its own Slater overlaps in
      R=R1/0.529167D0
C
C --- block.f 89-90: NATORB, how many atomic orbitals MOPAC gives each atom
      DATA NATORB/2*1, 4, 7*4, 0, 7*4, 0, 4, 9*9, 7*4,
     12*4, 9*9, 7*4, 2*2, 14*8, 9*9, 7*4, 15*0,1,5*0/
C
C --- block.f 454-463: the valence Slater exponents of all four hamiltonians
      DATA ZS3(1),ZP3(1)      /  1.3D0       ,  0.0D0      /
      DATA ZS3(5),ZP3(5)      /  1.211156D0 ,  0.972826D0 /
      DATA ZS3(6),ZP3(6)      /  1.739391D0 ,  1.709645D0 /
      DATA ZS3(7),ZP3(7)      /  2.704546D0 ,  1.870839D0 /
      DATA ZS3(8),ZP3(8)      /  3.640575D0 ,  2.168448D0 /
      DATA ZS3(9),ZP3(9)      /  3.111270D0 ,  1.41986D0 /
      DATA ZS3(14),ZP3(14)    /  1.629173D0 ,  1.381721D0 /
      DATA ZS3(15),ZP3(15)    /  1.926108D0 ,  1.590665D0 /
      DATA ZS3(16),ZP3(16)    /  1.719480D0 ,  1.403205D0 /
      DATA ZS3(17),ZP3(17)    /  3.430887D0 ,  1.627017D0 /
C
C --- block.f 536-536: the valence Slater exponents of all four hamiltonians
      DATA ZSM    ( 1)/       1.3319670D0/
C
C --- block.f 549-550: the valence Slater exponents of all four hamiltonians
      DATA ZSM    (  3)/       0.7023800D0/
      DATA ZPM    (  3)/       0.7023800D0/
C
C --- block.f 570-571: the valence Slater exponents of all four hamiltonians
      DATA ZSM    ( 4)/       1.0042100D0/
      DATA ZPM    ( 4)/       1.0042100D0/
C
C --- block.f 586-587: the valence Slater exponents of all four hamiltonians
      DATA ZSM    ( 5)/       1.5068010D0/
      DATA ZPM    ( 5)/       1.5068010D0/
C
C --- block.f 602-603: the valence Slater exponents of all four hamiltonians
      DATA ZSM    ( 6)/       1.7875370D0/
      DATA ZPM    ( 6)/       1.7875370D0/
C
C --- block.f 618-619: the valence Slater exponents of all four hamiltonians
      DATA ZSM    ( 7)/       2.2556140D0/
      DATA ZPM    ( 7)/       2.2556140D0/
C
C --- block.f 634-635: the valence Slater exponents of all four hamiltonians
      DATA ZSM    ( 8)/       2.6999050D0/
      DATA ZPM    ( 8)/       2.6999050D0/
C
C --- block.f 650-651: the valence Slater exponents of all four hamiltonians
      DATA ZSM    ( 9)/       2.8484870D0/
      DATA ZPM    ( 9)/       2.8484870D0/
C
C --- block.f 685-686: the valence Slater exponents of all four hamiltonians
      DATA ZSM    (13)/       1.4441610D0/
      DATA ZPM    (13)/       1.4441610D0/
C
C --- block.f 702-703: the valence Slater exponents of all four hamiltonians
      DATA ZSM    (14)/       1.3159860D0/
      DATA ZPM    (14)/       1.7099430D0/
C
C --- block.f 719-720: the valence Slater exponents of all four hamiltonians
      DATA ZSM    (15)/       2.1087200D0/
      DATA ZPM    (15)/       1.7858100D0/
C
C --- block.f 737-738: the valence Slater exponents of all four hamiltonians
      DATA ZSM    (16)/       2.3129620D0/
      DATA ZPM    (16)/       2.0091460D0/
C
C --- block.f 754-755: the valence Slater exponents of all four hamiltonians
      DATA ZSM    (17)/       3.7846450D0/
      DATA ZPM    (17)/       2.0362630D0/
C
C --- block.f 792-793: the valence Slater exponents of all four hamiltonians
      DATA ZSM    (24)/       1.5000000D0/
      DATA ZPM    (24)/       1.5000000D0/
C
C --- block.f 818-819: the valence Slater exponents of all four hamiltonians
      DATA ZSM   ( 30)/       2.0473590D0/
      DATA ZPM   ( 30)/       1.4609460D0/
C
C --- block.f 840-841: the valence Slater exponents of all four hamiltonians
      DATA ZSM   ( 32)/       1.2931800D0/
      DATA ZPM   ( 32)/       2.0205640D0/
C
C --- block.f 861-862: the valence Slater exponents of all four hamiltonians
      DATA ZSM    (35)/       3.8543019D0/
      DATA ZPM    (35)/       2.1992091D0/
C
C --- block.f 878-879: the valence Slater exponents of all four hamiltonians
      DATA ZSM    (50)/       2.0803800D0/
      DATA ZPM   (50)/       1.9371060D0/
C
C --- block.f 899-900: the valence Slater exponents of all four hamiltonians
      DATA ZSM    (53)/       2.2729610D0/
      DATA ZPM    (53)/       2.1694980D0/
C
C --- block.f 916-917: the valence Slater exponents of all four hamiltonians
      DATA ZSM    ( 80)/       2.2181840D0/
      DATA ZPM    ( 80)/       2.0650380D0/
C
C --- block.f 937-938: the valence Slater exponents of all four hamiltonians
      DATA ZSM    ( 82)/       2.4982860D0/
      DATA ZPM    ( 82)/       2.0820710D0/
C
C --- block.f 963-964: the valence Slater exponents of all four hamiltonians
      DATA ZSM    (90)/       1.4353060D0/
      DATA ZPM    (90)/       1.4353060D0/
C
C --- block.f 984-985: the valence Slater exponents of all four hamiltonians
      DATA ZSM    (91)/       2.6135910D0/
      DATA ZPM    (91)/       2.0343930D0/
C
C --- block.f 998-999: the valence Slater exponents of all four hamiltonians
      DATA ZSM   (102)/       4.0000000D0/
      DATA ZPM   (102)/       0.3000000D0/
C
C --- block.f 1020-1020: the valence Slater exponents of all four hamiltonians
      DATA ZS AM1( 1)/       1.1880780D0/
C
C --- block.f 1043-1044: the valence Slater exponents of all four hamiltonians
      DATA ZS AM1(  3)/       0.7023800D0/
      DATA ZP AM1(  3)/       0.7023800D0/
C
C --- block.f 1064-1065: the valence Slater exponents of all four hamiltonians
      DATA ZS AM1( 4)/       1.0042100D0/
      DATA ZP AM1( 4)/       1.0042100D0/
C
C --- block.f 1086-1087: the valence Slater exponents of all four hamiltonians
      DATA ZS AM1(  5)/       1.6117090D0/
      DATA ZP AM1(  5)/       1.5553850D0/
C
C --- block.f 1107-1108: the valence Slater exponents of all four hamiltonians
      DATA ZS AM1( 6)/       1.8086650D0/
      DATA ZP AM1( 6)/       1.6851160D0/
C
C --- block.f 1140-1141: the valence Slater exponents of all four hamiltonians
      DATA ZS AM1( 7)/       2.3154100D0/
      DATA ZP AM1( 7)/       2.1579400D0/
C
C --- block.f 1170-1171: the valence Slater exponents of all four hamiltonians
      DATA ZS AM1( 8)/       3.1080320D0/
      DATA ZP AM1( 8)/       2.5240390D0/
C
C --- block.f 1197-1198: the valence Slater exponents of all four hamiltonians
      DATA ZS AM1( 9)/       3.7700820D0/
      DATA ZP AM1( 9)/       2.4946700D0/
C
C --- block.f 1224-1225: the valence Slater exponents of all four hamiltonians
      DATA ZSAM1 ( 13)/       1.5165930D0/
      DATA ZPAM1 ( 13)/       1.3063470D0/
C
C --- block.f 1249-1250: the valence Slater exponents of all four hamiltonians
      DATA ZS AM1(14)/       1.830697D0/
      DATA ZP AM1(14)/       1.2849530D0/
C
C --- block.f 1280-1281: the valence Slater exponents of all four hamiltonians
      DATA ZS AM1( 15)/       1.9812800D0/
      DATA ZP AM1( 15)/       1.8751500D0/
C
C --- block.f 1312-1313: the valence Slater exponents of all four hamiltonians
      DATA ZS AM1(16)/       2.3665150D0/
      DATA ZP AM1(16)/       1.6672630D0/
C
C --- block.f 1343-1344: the valence Slater exponents of all four hamiltonians
      DATA ZS AM1(17)/       3.6313760D0/
      DATA ZP AM1(17)/       2.0767990D0/
C
C --- block.f 1371-1372: the valence Slater exponents of all four hamiltonians
      DATA ZS AM1( 30)/       1.9542990D0/
      DATA ZP AM1( 30)/       1.3723650D0/
C
C --- block.f 1393-1394: the valence Slater exponents of all four hamiltonians
      DATA ZS AM1( 32)/       1.2196310D0/
      DATA ZP AM1( 32)/       1.9827940D0/
C
C --- block.f 1414-1415: the valence Slater exponents of all four hamiltonians
      DATA ZS AM1(35)/       3.0641330D0/
      DATA ZP AM1(35)/       2.0383330D0/
C
C --- block.f 1442-1443: the valence Slater exponents of all four hamiltonians
      DATA ZS AM1(53)/       2.1028580D0/
      DATA ZP AM1(53)/       2.1611530D0/
C
C --- block.f 1470-1471: the valence Slater exponents of all four hamiltonians
      DATA ZS AM1( 80)/       2.0364130D0/
      DATA ZP AM1( 80)/       1.9557660D0/
C
C --- block.f 1496-1497: the valence Slater exponents of all four hamiltonians
      DATA ZSAM1  (90)/       1.4353060D0/
      DATA ZPAM1  (90)/       1.4353060D0/
C
C --- block.f 1517-1518: the valence Slater exponents of all four hamiltonians
      DATA ZSAM1  (91)/       2.6135910D0/
      DATA ZPAM1  (91)/       2.0343930D0/
C
C --- block.f 1537-1538: the valence Slater exponents of all four hamiltonians
      DATA ZSAM1  (102)/       4.0000000D0/
      DATA ZPAM1  (102)/       0.3000000D0/
C
C --- block.f 1557-1557: the valence Slater exponents of all four hamiltonians
      DATA ZSPM3 (  1)/       0.9678070D0/
C
C --- block.f 1577-1578: the valence Slater exponents of all four hamiltonians
      DATA ZSPM3 (  4)/       0.8774390D0/
      DATA ZPPM3 (  4)/       1.5087550D0/
C
C --- block.f 1604-1605: the valence Slater exponents of all four hamiltonians
      DATA ZSPM3 (  6)/       1.5650850D0/
      DATA ZPPM3 (  6)/       1.8423450D0/
C
C --- block.f 1631-1632: the valence Slater exponents of all four hamiltonians
      DATA ZSPM3 (  7)/       2.0280940D0/
      DATA ZPPM3 (  7)/       2.3137280D0/
C
C --- block.f 1658-1659: the valence Slater exponents of all four hamiltonians
      DATA ZSPM3 (  8)/       3.7965440D0/
      DATA ZPPM3 (  8)/       2.3894020D0/
C
C --- block.f 1685-1686: the valence Slater exponents of all four hamiltonians
      DATA ZSPM3 (  9)/       4.7085550D0/
      DATA ZPPM3 (  9)/       2.4911780D0/
C
C --- block.f 1712-1713: the valence Slater exponents of all four hamiltonians
      DATA ZSPM3 ( 12)/       0.6985520D0/
      DATA ZPPM3 ( 12)/       1.4834530D0/
C
C --- block.f 1739-1740: the valence Slater exponents of all four hamiltonians
      DATA ZSPM3 ( 13)/       1.7028880D0/
      DATA ZPPM3 ( 13)/       1.0736290D0/
C
C --- block.f 1767-1768: the valence Slater exponents of all four hamiltonians
      DATA ZSPM3 ( 14)/       1.6350750D0/
      DATA ZPPM3 ( 14)/       1.3130880D0/
C
C --- block.f 1795-1796: the valence Slater exponents of all four hamiltonians
      DATA ZSPM3 ( 15)/       2.0175630D0/
      DATA ZPPM3 ( 15)/       1.5047320D0/
C
C --- block.f 1823-1824: the valence Slater exponents of all four hamiltonians
      DATA ZSPM3 ( 16)/       1.8911850D0/
      DATA ZPPM3 ( 16)/       1.6589720D0/
C
C --- block.f 1851-1852: the valence Slater exponents of all four hamiltonians
      DATA ZSPM3 ( 17)/       2.2462100D0/
      DATA ZPPM3 ( 17)/       2.1510100D0/
C
C --- block.f 1879-1880: the valence Slater exponents of all four hamiltonians
      DATA ZSPM3 ( 30)/       1.8199890D0/
      DATA ZPPM3 ( 30)/       1.5069220D0/
C
C --- block.f 1907-1908: the valence Slater exponents of all four hamiltonians
      DATA ZSPM3 ( 31)/       1.8470400D0/
      DATA ZPPM3 ( 31)/       0.8394110D0/
C
C --- block.f 1934-1935: the valence Slater exponents of all four hamiltonians
      DATA ZSPM3 ( 32)/       2.2373526D0/
      DATA ZPPM3 ( 32)/       1.5924319D0/
C
C --- block.f 1961-1962: the valence Slater exponents of all four hamiltonians
      DATA ZSPM3 ( 33)/       2.6361770D0/
      DATA ZPPM3 ( 33)/       1.7038890D0/
C
C --- block.f 1988-1989: the valence Slater exponents of all four hamiltonians
      DATA ZSPM3 ( 34)/       2.8280510D0/
      DATA ZPPM3 ( 34)/       1.7325360D0/
C
C --- block.f 2015-2016: the valence Slater exponents of all four hamiltonians
      DATA ZSPM3 ( 35)/       5.3484570D0/
      DATA ZPPM3 ( 35)/       2.1275900D0/
C
C --- block.f 2043-2044: the valence Slater exponents of all four hamiltonians
      DATA ZSPM3 ( 48)/       1.6793510D0/
      DATA ZPPM3 ( 48)/       2.0664120D0/
C
C --- block.f 2064-2065: the valence Slater exponents of all four hamiltonians
      DATA ZSPM3 ( 49)/       2.0161160D0/
      DATA ZPPM3 ( 49)/       1.4453500D0/
C
C --- block.f 2091-2092: the valence Slater exponents of all four hamiltonians
      DATA ZSPM3 ( 50)/       2.3733280D0/
      DATA ZPPM3 ( 50)/       1.6382330D0/
C
C --- block.f 2118-2119: the valence Slater exponents of all four hamiltonians
      DATA ZSPM3 ( 51)/       2.3430390D0/
      DATA ZPPM3 ( 51)/       1.8999920D0/
C
C --- block.f 2145-2146: the valence Slater exponents of all four hamiltonians
      DATA ZSPM3 ( 52)/       4.1654920D0/
      DATA ZPPM3 ( 52)/       1.6475550D0/
C
C --- block.f 2172-2173: the valence Slater exponents of all four hamiltonians
      DATA ZSPM3 ( 53)/       7.0010130D0/
      DATA ZPPM3 ( 53)/       2.4543540D0/
C
C --- block.f 2200-2201: the valence Slater exponents of all four hamiltonians
      DATA ZSPM3 ( 80)/       1.4768850D0/
      DATA ZPPM3 ( 80)/       2.4799510D0/
C
C --- block.f 2227-2228: the valence Slater exponents of all four hamiltonians
      DATA ZSPM3 ( 81)/       6.8679210D0/
      DATA ZPPM3 ( 81)/       1.9694450D0/
C
C --- block.f 2254-2255: the valence Slater exponents of all four hamiltonians
      DATA ZSPM3 ( 82)/       3.1412890D0/
      DATA ZPPM3 ( 82)/       1.8924180D0/
C
C --- block.f 2281-2282: the valence Slater exponents of all four hamiltonians
      DATA ZSPM3 ( 83)/       4.9164510D0/
      DATA ZPPM3 ( 83)/       1.9349350D0/
C
C --- block.f 2306-2307: the valence Slater exponents of all four hamiltonians
      DATA ZSPM3 (102)/       4.0000000D0/
      DATA ZPPM3 (102)/       0.3000000D0/
C
C --- setupg.f 10-15: Stewart's STO-6G expansions, and the NQN they are indexed by
      ALLZ(1,1,1) =2.310303149D01
      ALLZ(2,1,1) =4.235915534D00
      ALLZ(3,1,1) =1.185056519D00
      ALLZ(4,1,1) =4.070988982D-01
      ALLZ(5,1,1) =1.580884151D-01
      ALLZ(6,1,1) =6.510953954D-02
C
C --- setupg.f 17-22: Stewart's STO-6G expansions, and the NQN they are indexed by
      ALLC(1,1,1) =9.163596280D-03
      ALLC(2,1,1) =4.936149294D-02
      ALLC(3,1,1) =1.685383049D-01
      ALLC(4,1,1) =3.705627997D-01
      ALLC(5,1,1) =4.164915298D-01
      ALLC(6,1,1) =1.303340841D-01
C
C --- setupg.f 24-29: Stewart's STO-6G expansions, and the NQN they are indexed by
      ALLZ(1,2,1) =2.768496241D01
      ALLZ(2,2,1) =5.077140627D00
      ALLZ(3,2,1) =1.426786050D00
      ALLZ(4,2,1) =2.040335729D-01
      ALLZ(5,2,1) =9.260298399D-02
      ALLZ(6,2,1) =4.416183978D-02
C
C --- setupg.f 31-36: Stewart's STO-6G expansions, and the NQN they are indexed by
      ALLC(1,2,1) =-4.151277819D-03
      ALLC(2,2,1) =-2.067024148D-02
      ALLC(3,2,1) =-5.150303337D-02
      ALLC(4,2,1) =3.346271174D-01
      ALLC(5,2,1) =5.621061301D-01
      ALLC(6,2,1) =1.712994697D-01
C
C --- setupg.f 38-43: Stewart's STO-6G expansions, and the NQN they are indexed by
      ALLZ(1,2,2) =5.868285913D00
      ALLZ(2,2,2) =1.530329631D00
      ALLZ(3,2,2) =5.475665231D-01
      ALLZ(4,2,2) =2.288932733D-01
      ALLZ(5,2,2) =1.046655969D-01
      ALLZ(6,2,2) =4.948220127D-02
C
C --- setupg.f 45-50: Stewart's STO-6G expansions, and the NQN they are indexed by
      ALLC(1,2,2) =7.924233646D-03
      ALLC(2,2,2) =5.144104825D-02
      ALLC(3,2,2) =1.898400060D-01
      ALLC(4,2,2) =4.049863191D-01
      ALLC(5,2,2) =4.012362861D-01
      ALLC(6,2,2) =1.051855189D-01
C
C --- setupg.f 52-63: Stewart's STO-6G expansions, and the NQN they are indexed by
      ALLZ(1,3,1) =3.273031938D00
      ALLZ(2,3,1) =9.200611311D-01
      ALLZ(3,3,1) =3.593349765D-01
      ALLZ(4,3,1) =8.636686991D-02
      ALLZ(5,3,1) =4.797373812D-02
      ALLZ(6,3,1) =2.724741144D-02
      ALLC(1,3,1) =-6.775596947D-03
      ALLC(2,3,1) =-5.639325779D-02
      ALLC(3,3,1) =-1.587856086D-01
      ALLC(4,3,1) =5.534527651D-01
      ALLC(5,3,1) =5.015351020D-01
      ALLC(6,3,1) =7.223633674D-02
C
C --- setupg.f 65-76: Stewart's STO-6G expansions, and the NQN they are indexed by
      ALLZ(1,3,2) =5.077973607D00
      ALLZ(2,3,2) =1.340786940D00
      ALLZ(3,3,2) =2.248434849D-01
      ALLZ(4,3,2) =1.131741848D-01
      ALLZ(5,3,2) =6.076408893D-02
      ALLZ(6,3,2) =3.315424265D-02
      ALLC(1,3,2) =-3.329929840D-03
      ALLC(2,3,2) =-1.419488340D-02
      ALLC(3,3,2) =1.639395770D-01
      ALLC(4,3,2) =4.485358256D-01
      ALLC(5,3,2) =3.908813050D-01
      ALLC(6,3,2) =7.411456232D-02
C
C --- setupg.f 78-89: Stewart's STO-6G expansions, and the NQN they are indexed by
      ALLZ(1,4,1) = 1.365346 D+00
      ALLZ(2,4,1) = 4.393213 D-01
      ALLZ(3,4,1) = 1.877069 D-01
      ALLZ(4,4,1) = 9.360270 D-02
      ALLZ(5,4,1) = 5.052263 D-02
      ALLZ(6,4,1) = 2.809354 D-02
      ALLC(1,4,1) = 3.775056 D-03
      ALLC(2,4,1) =-5.585965 D-02
      ALLC(3,4,1) =-3.192946 D-01
      ALLC(4,4,1) =-2.764780 D-02
      ALLC(5,4,1) = 9.049199 D-01
      ALLC(6,4,1) = 3.406258 D-01
C
C --- setupg.f 91-102: Stewart's STO-6G expansions, and the NQN they are indexed by
      ALLC(1,4,2) =-7.052075 D-03
      ALLC(2,4,2) =-5.259505 D-02
      ALLC(3,4,2) =-3.773450 D-02
      ALLC(4,4,2) = 3.874773 D-01
      ALLC(5,4,2) = 5.791672 D-01
      ALLC(6,4,2) = 1.221817 D-01
      ALLZ(1,4,2) = 1.365346 D+00
      ALLZ(2,4,2) = 4.393213 D-01
      ALLZ(3,4,2) = 1.877069 D-01
      ALLZ(4,4,2) = 9.360270 D-02
      ALLZ(5,4,2) = 5.052263 D-02
      ALLZ(6,4,2) = 2.809354 D-02
C
C --- setupg.f 104-115: Stewart's STO-6G expansions, and the NQN they are indexed by
      ALLZ(1,5,1) = 7.701420258D-01
      ALLZ(2,5,1) = 2.756268915D-01
      ALLZ(3,5,1) = 1.301847480D-01
      ALLZ(4,5,1) = 6.953441940D-02
      ALLZ(5,5,1) = 4.002545502D-02
      ALLZ(6,5,1) = 2.348388309D-02
      ALLC(1,5,1) = 1.267447151D-02
      ALLC(2,5,1) = 3.266734789D-03
      ALLC(3,5,1) =-4.307553999D-01
      ALLC(4,5,1) =-3.231998963D-01
      ALLC(5,5,1) = 1.104322879D+00
      ALLC(6,5,1) = 4.368498703D-01
C
C --- setupg.f 117-128: Stewart's STO-6G expansions, and the NQN they are indexed by
      ALLZ(1,5,2) = 7.701420258D-01
      ALLZ(2,5,2) = 2.756268915D-01
      ALLZ(3,5,2) = 1.301847480D-01
      ALLZ(4,5,2) = 6.953441940D-02
      ALLZ(5,5,2) = 4.002545502D-02
      ALLZ(6,5,2) = 2.348388309D-02
      ALLC(1,5,2) =-1.105673292D-03
      ALLC(2,5,2) =-6.243132446D-02
      ALLC(3,5,2) =-1.628476766D-01
      ALLC(4,5,2) = 3.210328714D-01
      ALLC(5,5,2) = 6.964579592D-01
      ALLC(6,5,2) = 1.493146125D-01
C
C --- setupg.f 130-141: Stewart's STO-6G expansions, and the NQN they are indexed by
      ALLZ(1,6,1) = 5.800292686D-01
      ALLZ(2,6,1) = 2.718262251D-01
      ALLZ(3,6,1) = 7.938523262D-02
      ALLZ(4,6,1) = 4.975088254D-02
      ALLZ(5,6,1) = 2.983643556D-02
      ALLZ(6,6,1) = 1.886067216D-02
      ALLC(1,6,1) = 4.554359511D-03
      ALLC(2,6,1) = 5.286443143D-02
      ALLC(3,6,1) =-7.561016358D-01
      ALLC(4,6,1) =-2.269803820D-01
      ALLC(5,6,1) = 1.332494651D+00
      ALLC(6,6,1) = 3.622518293D-01
C
C --- setupg.f 143-154: Stewart's STO-6G expansions, and the NQN they are indexed by
      ALLZ(1,6,2) = 6.696537714D-01
      ALLZ(2,6,2) = 1.395089793D-01
      ALLZ(3,6,2) = 8.163894960D-02
      ALLZ(4,6,2) = 4.586329272D-02
      ALLZ(5,6,2) = 2.961305556D-02
      ALLZ(6,6,2) = 1.882221321D-02
      ALLC(1,6,2) = 2.782723680D-03
      ALLC(2,6,2) =-1.282887780D-01
      ALLC(3,6,2) =-2.266255943D-01
      ALLC(4,6,2) = 4.682259383D-01
      ALLC(5,6,2) = 6.752048848D-01
      ALLC(6,6,2) = 1.091534212D-01
C
C --- setupg.f 158-180: Stewart's STO-6G expansions, and the NQN they are indexed by
         XI=ZS(NI)
         IA=I*4-3
         IB=IA+3
         IF(NI.LT.2) THEN
            NQN=1
         ELSEIF(NI.LT.10)THEN
            NQN=2
         ELSEIF(NI.LT.18)THEN
            NQN=3
         ELSEIF(NI.LT.36)THEN
            NQN=4
         ELSEIF(NI.LT.54)THEN
            NQN=5
         ELSE
            NQN=6
         ENDIF
         DO 20 K=IA,IB
            L=1
            IF(K.GT.IA) L=2
            IF(K.GT.IA) XI=ZP(NI)
            DO 10 J=1,6
               CC(K,J)=ALLC(J,NQN,L)
   10       ZZ(K,J)=ALLZ(J,NQN,L)*XI**2
C
C --- esp.rof 681-681: ELESP: the zeta² scaling, the normalisation, and MOPAC 7's own bohr
      DATA BOHR/0.529167D0/
C
C --- esp.rof 717-717: ELESP: the zeta² scaling, the normalisation, and MOPAC 7's own bohr
               EX(NPR+J)=ALLZ(J,1,1)*ZS(1)**2
C
C --- esp.rof 738-738: ELESP: the zeta² scaling, the normalisation, and MOPAC 7's own bohr
               EX(NPR+J)=ALLZ(J,NQN,1)*ZS(IAN(I))**2
C
C --- esp.rof 750-750: ELESP: the zeta² scaling, the normalisation, and MOPAC 7's own bohr
                  EX(NPR+J)=ALLZ(J,NQN,2)*ZP(IAN(I))**2
C
C --- esp.rof 766-770: ELESP: the zeta² scaling, the normalisation, and MOPAC 7's own bohr
      DO 90 I=1,NPR
         NORM=(2.D0*EX(I)/PI)**0.75D0*(4.D0*EX(I))**(IAM(I,1)/2.D0)/
     1   SQRT(DEX(2*IAM(I,1)-1))
         CC(I)=CC(I)*NORM
   90 CONTINUE
C
C --- esp.rof 957-967: ELESP: the zeta² scaling, the normalisation, and MOPAC 7's own bohr
      DOUBLE PRECISION FUNCTION DEX2(M)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      IF(M .LT. 2) THEN
         DEX2=1
      ELSE
         DEX2=1
         DO 10 I=1,M,2
   10    DEX2=DEX2*I
      ENDIF
      RETURN
      END
C
C --- esp.rof 1327-1327: ELESP: the zeta² scaling, the normalisation, and MOPAC 7's own bohr
      DATA BOHR/0.529167D0/
C
C --- esp.rof 1474-1474: ELESP: the zeta² scaling, the normalisation, and MOPAC 7's own bohr
      DATA BOHR/0.529167D0/
C
C --- esp.rof 1682-1682: ELESP: the zeta² scaling, the normalisation, and MOPAC 7's own bohr
      DATA BOHR/0.529167D0/
