import { defineConfig, globalIgnores } from 'eslint/config';
import ts from 'eslint-config-cheminfo-typescript';

export default defineConfig(
  // Anchored, because an unanchored `wasm` also matches `src/wasm` and an
  // unanchored `lib` also matches `scripts/lib`: both would be skipped
  // silently.
  globalIgnores([
    'build/**',
    'coverage/**',
    'lib/**',
    // The base64 payload and the emscripten glue, generated by
    // `npm run build-wasm`, plus the hand-written declarations beside them.
    'wasm/**',
  ]),
  ts,
  {
    // The emscripten runtime exposes mixed-case members that are not constructors.
    rules: { 'new-cap': ['error', { capIsNew: false }] },
  },
  {
    // The build, verification and benchmark scripts are node command-line entry
    // points: printing is their output, and a non-zero exit is how they fail.
    files: ['benchmark/**', 'scripts/**'],
    languageOptions: { globals: { Buffer: 'readonly', process: 'readonly' } },
    rules: { 'no-console': 'off', 'unicorn/no-process-exit': 'off' },
  },
);
