/**
 * Which regions of the MOPAC 7 archive carry the basis-set tables, and how to
 * copy them out verbatim.
 *
 * The excerpt this writes is the fixture
 * `src/basis/__tests__/basisTables.test.ts` re-parses on every CI run, where
 * `build/` is absent. Every line of it is copied from the archive byte for byte,
 * under a header naming the file and the line range it came from, so there is
 * nothing in it a reader cannot check against the original.
 */

/** Every array the exponent tables are read from, by its `block.f` name. */
export const EXPONENT_ARRAYS = [
  'ZSM',
  'ZPM',
  'ZSAM1',
  'ZPAM1',
  'ZSPM3',
  'ZPPM3',
  'ZS3',
  'ZP3',
];

/** Every region of the archive the tables are read from, in excerpt order. */
const REGIONS = [
  {
    file: 'moldat.f',
    why: 'which exponent array each hamiltonian switches in',
    ranges: (lines) => matches(lines, /^ +Z[SP]\(I\)=Z[SP][A-Z\d]*\(I\)$/),
  },
  {
    file: 'diat.f',
    why: 'NPQ, the principal quantum number of the valence shell',
    ranges: (lines) => [statement(lines, 'DATA NPQ/')],
  },
  {
    file: 'diat.f',
    why: 'the bohr MOPAC 7 computes its own Slater overlaps in',
    ranges: (lines) => matches(lines, /R=R1\/0\.529167D0/),
  },
  {
    file: 'block.f',
    why: 'NATORB, how many atomic orbitals MOPAC gives each atom',
    ranges: (lines) => [statement(lines, 'DATA NATORB/')],
  },
  {
    file: 'block.f',
    why: 'the valence Slater exponents of all four hamiltonians',
    ranges: (lines) => dataStatements(lines, EXPONENT_ARRAYS),
  },
  {
    file: 'setupg.f',
    why: "Stewart's STO-6G expansions, and the NQN they are indexed by",
    ranges: (lines) => [
      ...matches(lines, /^ {6}ALL[ZC]\(\d+,\d+,\d+\) *=/),
      ...matches(lines, /^ {9}XI=ZS\(NI\)$/, 22),
    ],
  },
  {
    file: 'esp.rof',
    why: "ELESP: the zeta² scaling, the normalisation, and MOPAC 7's own bohr",
    ranges: (lines) => [
      ...matches(lines, /^ {6}DATA BOHR\/0\.529167D0\/$/),
      ...matches(lines, /EX\(NPR\+J\)=ALLZ\(J,[^)]*\)\*Z[SP]\(/),
      ...matches(lines, /^ {6}DO 90 I=1,NPR$/, 4),
      ...matches(lines, /^ {6}DOUBLE PRECISION FUNCTION DEX2\(M\)$/, 10),
    ],
  },
];

/**
 * Copy every region out of the archive, under a provenance header.
 * @param {Map<string, string[]>} sources - Archive file name to its split lines.
 * @param {object} source - The `source` block of `wasm/BUILD.json`.
 * @returns {string} The excerpt, ending in a newline.
 */
export function buildBasisExcerpt(sources, source) {
  const excerpt = [
    'C =====================================================================',
    'C  The basis-set tables of MOPAC 7, excerpted from',
    `C    ${source.repository}`,
    `C    commit ${source.commit}, subdirectory ${source.subdirectory}`,
    `C    tree sha256 ${source.treeSha256}`,
    'C',
    'C  GENERATED by scripts/generate-basis-tables.mjs. Do not edit.',
    'C',
    'C  It exists so src/basis/__tests__/basisTables.test.ts can re-parse',
    "C  MOPAC's own Fortran on every machine and every CI run, where the",
    'C  archive under build/ is absent. Every line below is copied verbatim',
    'C  from the file and lines its header names, and the generator refuses',
    'C  to write a table the excerpt does not reproduce.',
    'C =====================================================================',
  ];
  for (const region of REGIONS) {
    const lines = sources.get(region.file);
    if (lines === undefined) throw new Error(`${region.file} was not read`);
    for (const [start, end] of merge(region.ranges(lines))) {
      excerpt.push(
        'C',
        `C --- ${region.file} ${start}-${end}: ${region.why}`,
        ...lines.slice(start - 1, end),
      );
    }
  }
  return `${excerpt.join('\n')}\n`;
}

/**
 * Line numbers of every line matching a pattern.
 * @param {string[]} lines - The file, split.
 * @param {RegExp} pattern - What to look for.
 * @param {number} extra - How many following lines belong to the match.
 * @returns {Array<number[]>} One `[start, end]` range per hit, 1-based and inclusive.
 */
function matches(lines, pattern, extra = 0) {
  const found = [];
  for (let index = 0; index < lines.length; index++) {
    if (pattern.test(lines[index])) found.push([index + 1, index + 1 + extra]);
  }
  if (found.length === 0) throw new Error(`no line matches ${pattern}`);
  return found;
}

/**
 * Line numbers of every `DATA <name>(…)/…/` statement of the named arrays.
 * @param {string[]} lines - The file, split.
 * @param {string[]} names - Array names, blanks removed.
 * @returns {Array<number[]>} One single-line range per statement.
 */
function dataStatements(lines, names) {
  const wanted = new Set(names);
  const found = [];
  for (let index = 0; index < lines.length; index++) {
    const line = lines[index];
    if (/^[*cC!]/.test(line)) continue;
    const squeezed = line.replaceAll(' ', '');
    if (!squeezed.startsWith('DATA')) continue;
    let hit = false;
    for (const name of squeezed.slice(4).matchAll(/(?<array>[A-Z\d]+)\(/g)) {
      if (wanted.has(name.groups?.array)) hit = true;
    }
    if (hit) found.push([index + 1, index + 1]);
  }
  if (found.length === 0) {
    throw new Error(`no DATA statement for ${[...names]}`);
  }
  return found;
}

/**
 * The full extent of a whole-array `DATA <name>/…/`, continuation lines included.
 * @param {string[]} lines - The file, split.
 * @param {string} head - The squeezed statement head, e.g. `DATA NPQ/`.
 * @returns {number[]} The `[start, end]` range, 1-based and inclusive.
 */
function statement(lines, head) {
  const squeezedHead = head.replaceAll(' ', '');
  for (let index = 0; index < lines.length; index++) {
    if (!lines[index].replaceAll(' ', '').startsWith(squeezedHead)) continue;
    let end = index;
    while (isContinuation(lines[end + 1])) end++;
    return [index + 1, end + 1];
  }
  throw new Error(`no ${head} statement`);
}

/**
 * Whether a line continues the previous statement: fixed form says column 6 is
 * not blank, and a comment line is never a continuation whatever it holds there.
 * @param {string|undefined} line - The candidate line, or `undefined` past the end of the file.
 * @returns {boolean} `true` when it continues.
 */
function isContinuation(line) {
  if (line === undefined || line.length < 6) return false;
  return !/^[*cC!]/.test(line) && line[5] !== ' ';
}

/**
 * Sort and coalesce ranges that touch or overlap.
 * @param {Array<number[]>} ranges - `[start, end]` pairs.
 * @returns {Array<number[]>} The merged ranges, in file order.
 */
function merge(ranges) {
  const sorted = [...ranges].toSorted((a, b) => a[0] - b[0]);
  const merged = [];
  for (const [start, end] of sorted) {
    const last = merged.at(-1);
    if (last !== undefined && start <= last[1] + 1) {
      last[1] = Math.max(last[1], end);
      continue;
    }
    merged.push([start, end]);
  }
  return merged;
}
