/**
 * Turn the parsed Fortran tables into the two TypeScript modules under
 * `src/basis/`. Nothing here decides a number; it only lays out what
 * `parseBasisFortran` read, and fails loudly on anything that does not add up.
 */

import { MOPAC7_ELEMENTS, elementNumber } from '../../src/input/elements.ts';

/**
 * `src/basis/sto6g.ts`: MOPAC's STO-6G table, indexed by `n - 1` then `l`.
 * @param {object} tables - From `parseBasisFortran`.
 * @param {string} header - The provenance comment, from {@link moduleHeader}.
 * @returns {string} The module source.
 */
export function sto6gModule(tables, header) {
  const rows = tables.sto6g.map((row, n) => {
    const shells = [0, 1].map((l) => {
      const shell = row[l] ?? null;
      if (shell === null) return 'null';
      return `{ alpha: [${shell.alpha.join(', ')}], coefficient: [${shell.coefficient.join(', ')}] }`;
    });
    return `  // n = ${n + 1}\n  [${shells.join(', ')}],`;
  });
  return `${header}
import type { Mopac7StoExpansion } from './types.ts';

/**
 * Stewart's STO-6G expansions, exactly as MOPAC 7's \`setupg.f\` \`SETUPG\` writes
 * them, indexed by principal quantum number minus one and then by \`l\`.
 *
 * These are the unscaled, unnormalised numbers. \`esp.rof\` \`ELESP\` turns one
 * entry into a contracted gaussian by multiplying every exponent by \`zeta²\` and
 * folding the cartesian normalisation into every coefficient; see
 * \`contractSlaterShell\`.
 *
 * MOPAC 7's own \`COMMON /STO6G/\` is declared \`(6,5,2)\`, so the 6s and 6p blocks
 * \`SETUPG\` assigns fall past its end and MOPAC itself cannot read them back.
 * They are read from the source here, which is why mercury, thallium, lead and
 * bismuth have a basis at all.
 */
// prettier-ignore
export const MOPAC7_STO6G: ReadonlyArray<
  ReadonlyArray<Mopac7StoExpansion | null>
> = [
${rows.join('\n')}
];
`;
}

/**
 * `src/basis/slaterExponents.ts`: the per-element valence exponents, for every
 * element each hamiltonian accepts and `NATORB` gives an atomic orbital to.
 * @param {object} tables - From `parseBasisFortran`.
 * @param {string} header - The provenance comment, from {@link moduleHeader}.
 * @returns {string} The module source.
 */
export function exponentsModule(tables, header) {
  const blocks = [];
  const sparkles = new Map();
  for (const [method, symbols] of Object.entries(MOPAC7_ELEMENTS)) {
    const entries = [];
    for (const symbol of symbols) {
      const line = elementLine(tables, method, symbol);
      if (line === null) {
        sparkles.set(symbol, (sparkles.get(symbol) ?? []).concat(method));
        continue;
      }
      entries.push(line);
    }
    blocks.push(`  ${method}: {\n${entries.join('\n')}\n  },`);
  }
  const sparkleNote = [...sparkles]
    .map(([symbol, methods]) => `${symbol} (${methods.join(', ')})`)
    .join(', ');
  return `${header}
import type { Mopac7Method } from '../types.ts';

import type { Mopac7ElementBasis } from './types.ts';

/**
 * The valence Slater exponents and principal quantum numbers of every element
 * each hamiltonian can draw, read out of MOPAC 7's own \`block.f\` and \`diat.f\`.
 *
 * The keys are the element symbols of \`MOPAC7_ELEMENTS\` minus the ones MOPAC
 * parameterises as sparkles — ${sparkleNote} —
 * which carry a point charge and no exponent, and to which \`NATORB\` gives no
 * atomic orbital at all.
 */
// prettier-ignore
export const MOPAC7_SLATER_EXPONENTS: Record<
  Mopac7Method,
  Readonly<Record<string, Mopac7ElementBasis>>
> = {
${blocks.join('\n')}
};
`;
}

/**
 * The provenance header a generated module carries.
 * @param {object} source - The `source` block of `wasm/BUILD.json`.
 * @param {string} file - The archive file it came from.
 * @param {string} what - The statements read out of it.
 * @returns {string} The comment block.
 */
export function moduleHeader(source, file, what) {
  return `// GENERATED by scripts/generate-basis-tables.mjs from
// ${source.repository} commit ${source.commit},
// ${source.subdirectory}/${file} (${what}).
// Do not edit: run \`node scripts/generate-basis-tables.mjs\` instead.
`;
}

/**
 * One element's entry, or `null` when MOPAC gives it no atomic orbital.
 * @param {object} tables - From `parseBasisFortran`.
 * @param {string} method - The hamiltonian.
 * @param {string} symbol - The element symbol.
 * @returns {string|null} The source line, or `null` for a sparkle.
 */
function elementLine(tables, method, symbol) {
  const atomicNumber = elementNumber(symbol);
  const orbitalCount = tables.orbitalCount[atomicNumber - 1];
  const exponents = tables.exponents[method].get(atomicNumber);
  if (orbitalCount === 0) {
    if (exponents !== undefined) {
      throw new Error(`${method} ${symbol}: NATORB 0 but an exponent exists`);
    }
    return null;
  }
  if (exponents === undefined) {
    throw new Error(`${method} ${symbol}: no exponent in the Fortran`);
  }
  const n = tables.principalQuantumNumber[atomicNumber - 1];
  if (!(n >= 1 && n <= 6)) throw new Error(`${method} ${symbol}: NPQ is ${n}`);
  if (orbitalCount >= 4 && exponents.p === null) {
    throw new Error(`${method} ${symbol}: NATORB ${orbitalCount} but no ZP`);
  }
  return (
    `    ${`${symbol}:`.padEnd(4)} { atomicNumber: ${String(atomicNumber).padStart(3)}, ` +
    `principalQuantumNumber: ${n}, orbitalCount: ${orbitalCount}, ` +
    `zetaS: ${String(exponents.s).padEnd(9)}, zetaP: ${exponents.p} },`
  );
}
