/**
 * Turn the linker's output into the two JavaScript modules the package ships.
 *
 * The WebAssembly binary lives INSIDE the JavaScript, gzipped and base64'd, so
 * a consumer has no `.wasm` file to serve, no bundler plugin to install and no
 * `locateFile` to configure. This is the distribution pattern cheminfo/inchi-js
 * introduced and cheminfo/openchemlib-search-wasm refined; three details are
 * taken from the latter and each one is load-bearing:
 *
 *   the payload is emitted as `.js` + a hand-written `.d.ts`, never `.ts`, so
 *     `tsc --project tsconfig.build.json` compiles src/ to lib/ without pulling
 *     a 400 kB string literal through the type checker. `lib/wasm/*.js` and
 *     `src/wasm/*.ts` sit at the same depth, so `../../wasm/data.js` resolves
 *     from both.
 *   byte 9 of a gzip member is the OS identifier, and node writes 0x13 on
 *     macOS against 0x03 on Linux. It is normalised to 0xff (unknown) so the
 *     same input produces the same file on every machine.
 *   the recorded digest is of what the payload DECOMPRESSES TO, never of the
 *     payload itself: deflate output differs between node releases on identical
 *     input, so hashing the compressed bytes would fail a rebuild that changed
 *     nothing.
 *
 * Usage: node scripts/embed-wasm.mjs [--wasm-dir DIR] [--sizes FILE]
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { gzipSync } from 'node:zlib';

const REPO_ROOT = join(import.meta.dirname, '..');
const options = readOptions(process.argv.slice(2));
const wasmDirectory = options['wasm-dir'] ?? join(REPO_ROOT, 'wasm');
const sizesFile =
  options.sizes ?? join(REPO_ROOT, 'build', 'mopac7-fortran', 'SIZES');

const wasm = readFileSync(join(wasmDirectory, 'mopac7.wasm'));
const glue = readFileSync(join(wasmDirectory, 'mopac7.mjs'));
const buildFile = join(wasmDirectory, 'BUILD.json');
const build = JSON.parse(readFileSync(buildFile, 'utf8'));

const gzipped = gzipSync(wasm, { level: 9 });
// Byte 9 is the OS identifier. 0xff is "unknown", which is what makes the
// output reproducible across macOS and Linux.
gzipped[9] = 0xff;
const base64 = gzipped.toString('base64');

const dataModule =
  `// @generated by scripts/embed-wasm.mjs from mopac7.wasm -- do not edit.\n` +
  `// MOPAC 7.00 (public domain, QCPE #688), gzip -9 then base64.\n` +
  `export const wasmGzipBase64 =\n  '${base64}';\n`;
writeFileSync(join(wasmDirectory, 'data.js'), dataModule);
writeFileSync(
  join(wasmDirectory, 'data.d.ts'),
  `// @generated by scripts/embed-wasm.mjs -- do not edit.\n` +
    `/** The MOPAC 7 WebAssembly module, gzipped and base64-encoded. */\n` +
    `export declare const wasmGzipBase64: string;\n`,
);

const glueModule =
  `// @generated by scripts/embed-wasm.mjs from mopac7.mjs -- do not edit.\n` +
  `// Emscripten ES6 module factory, linked with -sENVIRONMENT=web,worker so it\n` +
  `// carries no node branch for a bundler to trip over.\n${glue.toString('utf8')}`;
writeFileSync(join(wasmDirectory, 'glue.js'), glueModule);
// wasm/glue.d.ts is hand-written and committed: emscripten emits no
// declarations, and the three members the package uses never change.

build.limits = readSizes(sizesFile);
build.payload = {
  what: 'wasm/data.js and wasm/glue.js, the two modules the npm package ships',
  wasmBytes: wasm.length,
  wasmSha256: build.sha256['mopac7.wasm'],
  gzipBytes: gzipped.length,
  base64Characters: base64.length,
  dataModuleBytes: Buffer.byteLength(dataModule),
  glueModuleBytes: Buffer.byteLength(glueModule),
  note: 'wasmSha256 is the digest of the DECOMPRESSED module, which is what src/__tests__ checks; the gzip stream itself is not reproducible across node releases.',
};
writeFileSync(buildFile, `${JSON.stringify(build, null, 2)}\n`);

process.stdout.write(
  `embed-wasm: data.js ${base64.length} chars (gzip ${gzipped.length} B of ${wasm.length} B), ` +
    `glue.js ${glue.length} B, limits ${JSON.stringify(build.limits)}\n`,
);

/**
 * Read the compiled array bounds out of MOPAC's own SIZES include file, so the
 * limit the wrapper enforces is always the limit the binary was built with.
 * @param {string} file - Path to the SIZES file used for this build.
 * @returns {{maxHeavyAtoms: number, maxHydrogenAtoms: number, maxAtoms: number, maxOrbitals: number}} The bounds.
 */
function readSizes(file) {
  const text = readFileSync(file, 'utf8');
  const match =
    /PARAMETER\s*\(\s*MAXHEV\s*=\s*(?<heavy>\d+)\s*,\s*MAXLIT\s*=\s*(?<light>\d+)\s*\)/.exec(
      text,
    );
  if (match?.groups === undefined) {
    throw new Error(`no "PARAMETER (MAXHEV=..., MAXLIT=...)" line in ${file}`);
  }
  const maxHeavyAtoms = Number(match.groups.heavy);
  const maxHydrogenAtoms = Number(match.groups.light);
  return {
    maxHeavyAtoms,
    maxHydrogenAtoms,
    // SIZES: NUMATM = MAXHEV + MAXLIT, MAXORB = 4 * MAXHEV + MAXLIT.
    maxAtoms: maxHeavyAtoms + maxHydrogenAtoms,
    maxOrbitals: 4 * maxHeavyAtoms + maxHydrogenAtoms,
  };
}

function readOptions(argv) {
  const parsed = {};
  for (let index = 0; index < argv.length; index += 2) {
    const key = argv[index];
    if (key === undefined || !key.startsWith('--')) {
      throw new Error(`expected an option, found ${String(key)}`);
    }
    const value = argv[index + 1];
    if (value === undefined) throw new Error(`${key} has no value`);
    parsed[key.slice(2)] = value;
  }
  return parsed;
}
